package db

const adminsCreateSQL = `DROP TABLE IF EXISTS ADMINS_TB;
CREATE TABLE ADMINS_TB (
    UID  VARCHAR(32) PRIMARY KEY,
    PWD  TEXT        NOT NULL,
    TIME TEXT        DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO ADMINS_TB (UID, PWD)
VALUES ('root', '19971213');`

const adminsQuerySQL = `SELECT UID, PWD FROM ADMINS_TB`
const adminsInsertSQL = `INSERT INTO ADMINS_TB (UID, PWD) VALUES (?, ?)`
const adminsDeleteSQL = `DELETE FROM ADMINS_TB WHERE UID = '?'`

const roomsCreateSQL = `DROP TABLE IF EXISTS ROOMS_TB;
CREATE TABLE ROOMS_TB (
    RID   VARCHAR(64) PRIMARY KEY,
    ADMIN VARCHAR(32) REFERENCES ADMINS_TB(UID),
    TOKEN VARCHAR(20) NOT NULL,
    TIME  TEXT        DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO ROOMS_TB (RID, ADMIN, TOKEN)
VALUES ('237', 'root', 'shining237');`
const roomsQuerySQL = `SELECT RID, ADMIN, TOKEN FROM ROOMS_TB`
const roomsInsertSQL = `INSERT INTO ROOMS_TB (RID, ADMIN, TOKEN) VALUES (?, ?, ?)`
const roomsDeleteSQL = `DELETE FROM ROOMS_TB WHERE RID = '?'`
